version: 2

models:
  - name: initial_raw_dataset
    description: "The primary staging model for raw ads cluster data."
    config:
      contract:
        enforced: true
    columns:
      - name: new_ts
        data_type: timestamp
        tests:
          - not_null
      - name: machine_id
        data_type: int64
        tests:
          - not_null
      - name: unique_machines
        data_type: int64
        description: "Number of unique machines in this minute bucket."
      - name: avg_cpu
        data_type: float64
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 100
      - name: avg_memory
        data_type: float64
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

  - name: average_metrics
    description: "Daily aggregated metrics per minute."
    columns:
      - name: new_ts
        tests:
          - not_null
          - unique
